### ISSUE TITLE
primary keys check and error's alias

### ISSUE THREAD

**Issue by brunettig** [mikulskibartosz/pyspark-check#7]
hi, I have two suggestions for some personal use cases:
- check on primary keys of dataframe:
   it would be great to add a function that checks the primary key on a list of columns
- add a custom alias to error
  you should be able to enter an alias as an argument of the method in order to recognize it in errors

thank you so much for the work

**Comment by mikulskibartosz** [comment]
Hi, thank you for the suggestions.

How would you like it to work? Should the primary key check verify the uniqueness of values? The library already supports it.

Could you write an example here of both use cases explaining the input data, the setup you would like to see and the expected output?

**Comment by brunettig** [comment]
Currently the "are_unique" function checks columns only individually with a loop on "is_unique".
ex:
ID_1; ID_2
1; 2
1: 1
2; 2

ID_1 and ID_2 are not unique individually, but they are when you concatenate them.

**Comment by brunettig** [comment]
Alias as an optional argument would be handy for generating an error report.
for example:

result = ValidateSparkDataFrame (spark_session, spark_data_frame) \
         .is_not_null ("ID_1", alias = 'ERROR_1 ") \
         .is_not_null ("ID_2", alias = 'ERROR_2 "). execute ()

result.errors

[ValidationError (column_name = 'ID_1', constraint_name = 'is_not_null', number_of_errors = 17, alias = "ERROR_1"),
  ValidationError (column_name = 'ID_2', constraint_name = 'is_not_null', number_of_errors = 2, alias = "ERROR_2")]
